server:
  port: 8090

spring:
  application:
    name: EcoMada Collect
  datasource:
    url: jdbc:h2:mem:ecomadadb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

jwt:
  secret: ZWNvbWFkYUNvbGxlY3RTZWNyZXRLZXlGb3JKV1RBdXRoZW50aWNhdGlvbjIwMjY=
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
